import { FeedVideo } from "@/components/VideoFeed";

export const sampleVideos: FeedVideo[] = [
  {
    id: "1",
    src: "https://gateway.lighthouse.storage/ipfs/bafybeigduaiqjx2stybjkajueckpaevt4wxfnela6mes42sh3kzr2k5nmy",
    caption: "Demo Trader Video 📈",
    author: "user1",
    likes: 1247,
    vault: {
      title: "Insiders Club",
      username: "cryptowhale",
      liquidity: "$52m",
      yield: "+12.5%",
      timeAgo: "1 day ago",
      earnings: "+$108.9",
      invested: "$4203.48",
      since: "1 year ago",
      variant: "dark",
    },
  },
  {
    id: "2",
    src: "https://gateway.lighthouse.storage/ipfs/bafybeihxik6jnwhuypyx6penmkkcbdn7gpxvinyzhmmq3uwl76sfoyw6aq",
    caption: "Trading Tutorial: Basic Strategies 💰",
    author: "user2",
    likes: 892,
    vault: {
      title: "DrizzleDAO",
      username: "drizzle.eth",
      liquidity: "$3.7m",
      yield: "+3.3%",
      timeAgo: "2 hours ago",
      earnings: "+$108.9",
      invested: "$4203.48",
      since: "3mo ago",
      variant: "dark",
    },
  },
  {
    id: "3",
    src: "https://gateway.lighthouse.storage/ipfs/bafybeiag24nkbhi3tnyp7sgwy22u7fn7k2owobbfm22luv7ykn6bqap2ke",
    caption: "Market Analysis: Daily Review 📊",
    author: "user3",
    likes: 2156,
    vault: {
      title: "Binge",
      username: "binge.eth",
      liquidity: "$52m",
      yield: "+12.5%",
      timeAgo: "3 days ago",
      earnings: "+$108.9",
      invested: "$4203.48",
      since: "3mo ago",
      variant: "dark",
    },
  },
  {
    id: "4",
    src: "https://gateway.lighthouse.storage/ipfs/bafybeihxik6jnwhuypyx6penmkkcbdn7gpxvinyzhmmq3uwl76sfoyw6aq",
    caption: "Risk Management in Trading 🛡️",
    author: "user4",
    likes: 3456,
    vault: {
      title: "DrizzleDAO",
      username: "drizzle.eth",
      liquidity: "$3.7m",
      yield: "+12.5%",
      timeAgo: "1 day ago",
      earnings: "+$108.9",
      invested: "$4203.48",
      since: "3mo ago",
      variant: "dark",
    },
  },
];
